---
title: "Assignment_3"
author: "Anthony Munoz"
date: "2/11/2019"
output: html_document
---
##3-a
```{r}
library(stringr)

raw.data <-"555-1239Moe Szyslak(636) 555-0113Burns, C. Montgomery555-6542Rev. Timothy Lovejoy555 8904Ned Flanders636-555-3226Simpson, Homer5553642Dr. Julius Hibbert"
```


```{r}
regex <- "([a-zA-Z,. ]){2,}"
name <- unlist(str_extract_all(raw.data, regex))
name
str(name)
data.name <- str_remove_all(name,"(\\w+)\\.\\s")
data.name
data.name <-gsub("(\\w+)\\,\\s(.*)","\\2 \\1", data.name)
df <- data.frame(str_split_fixed(data.name, " ", 2))
colnames(df) <- c("First Name","Last Name")
df
```


##9
```{r}
data <- "clcopCow1zmstc0d87wnkig7OvdicpNuggvhryn92Gjuwczi8hqrfpRxs5Aj5dwpn0Tanwo\nUwisdij7Lj8kpf03AT5Idr3coc0bt7yczjatOaootj55t3Nj3ne6c4Sfek.r1w1YwwojigO\nd6vrfUrbz2.2bkAnbhzgv4R9i05zEcrop.wAgnb.SqoU65fPa1otfb7wEm24k6t3sR9zqe5\nfy89n6Nd5t9kc4fE905gmc4Rgxo5nhDk!gr"

data <- paste(unlist(str_extract_all(data,"[A-Z]")), collapse = "")
gsub("(.{15})(.{3})(.{3})(.{1})(.{5})(.{4})","\\1 \\2 \\3 \\4 \\5 \\6", data)


```
